sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION="Django>=1.11,<2.1"
  - DJANGO_VERSION="Django>=2.0,<2.1"
  - DJANGO_VERSION="Django>=2.1,<2.2"
  - DJANGO_VERSION="Django>=2.2,<3.0"
  - DJANGO_VERSION="Django>=3.0,<3.1"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install -r test_requirements.txt
  - pip install -q $DJANGO_VERSION
script: python -Wall $VIRTUAL_ENV/bin/coverage run webmap/tests/runtests.py
before_script:
  - django-admin --version
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
addons:
  postgresql: "10"
  apt:
     packages:
        - postgresql-10-postgis-2.5
        - libgdal-dev
        - gdal-bin
after_script:
  - coveralls
matrix:
   exclude:
      - python: "3.5"
        env: DJANGO_VERSION="Django>=3.0,<3.1"
      - python: "3.5"
        env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
