sudo: false
language: python
python:
  - "3.4"
  - "2.7"
env:
  - DJANGO_VERSION="Django>=1.7,<1.8"
  - DJANGO_VERSION="Django>=1.8,<1.9"
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install -q "$DJANGO_VERSION"
  - pip install -r test_requirements.txt
script: python -Wall $VIRTUAL_ENV/bin/coverage run webmap/tests/runtests.py
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
addons:
  postgresql: "9.3"
after_script:
  - coveralls
matrix:
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
