language: python
python:
  - "2.7"
install:
  - pip install -r test_requirements.txt
  - python manage.py migrate
script: python webmap/tests/runtests.py
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
addons:
  postgresql: "9.3"
